# Generated by Django 4.1.7 on 2023-05-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodingProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("level", models.IntegerField()),
                ("content_problem", models.CharField(max_length=200)),
                ("content_input", models.CharField(max_length=200)),
                ("content_output", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="EthicsProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("content", models.CharField(max_length=200)),
                ("optionA", models.CharField(max_length=100)),
                ("optionB", models.CharField(max_length=100)),
                ("submissionA", models.CharField(max_length=300)),
                ("submissionB", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="SolvedEthics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sogongapp.ethicsproblem",
                        to_field="title",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sogongapp.user",
                        to_field="username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolvedCoding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sogongapp.codingproblem",
                        to_field="title",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sogongapp.user",
                        to_field="username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodingTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_input1", models.CharField(max_length=100)),
                ("case_input2", models.CharField(max_length=100)),
                ("case_input3", models.CharField(max_length=100)),
                ("case_input4", models.CharField(max_length=100)),
                ("case_output1", models.CharField(max_length=100)),
                ("case_output2", models.CharField(max_length=100)),
                ("case_output3", models.CharField(max_length=100)),
                ("case_output4", models.CharField(max_length=100)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sogongapp.codingproblem",
                        to_field="title",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodingSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gpt_answer", models.CharField(max_length=200)),
                ("user_submission", models.CharField(max_length=200)),
                ("gpt_feedback", models.CharField(max_length=200)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sogongapp.codingproblem",
                        to_field="title",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sogongapp.user",
                        to_field="username",
                    ),
                ),
            ],
        ),
    ]
